name: Build and Push Docker Image from Tag

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to write to GitHub Packages (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags. Neccessary to calculate version in conan
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has necessary permissions

      - name: compile arduino and linux apps
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/larsindresaeter/radio-arduino-devbox:1.0.0
          options: --user 1001:1001 -v ${{ github.workspace }}:/home/raduino
          run: |
            ./tools/scripts/setup.sh all
            ./tools/scripts/build.sh all

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # The name of your image repository
          tags: |
            type=semver,pattern={{version}} # Extracts semantic version from the Git tag (e.g., v1.0.0 -> 1.0.0)
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./tools/docker/app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Uses the tags generated by the metadata action
          labels: ${{ steps.meta.outputs.labels }}

